/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author João Arthur JR
 */
class MyCustomFilter extends javax.swing.filechooser.FileFilter {

    @Override
    public boolean accept(File file) {
        // Allow only directories, or files with ".txt" extension
        return file.isDirectory() || file.getAbsolutePath().endsWith(".txt");
    }

    @Override
    public String getDescription() {
        // This description will be displayed in the dialog,
        // hard-coded = ugly, should be done via I18N
        return "Text documents (*.txt)";
    }
}

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
//    URL url = this.getClass().getResource("logo_fimm.png");
//    Image icone = Toolkit.getDefaultToolkit().getImage(url);
//    
//
//    @Override
//    public void setIconImage(Image image) {
//        super.setIconImage(image); //To change body of generated methods, choose Tools | Templates.
//    }
    
    
    public TelaPrincipal() {
        try {
            Thread.sleep(2000);//tempo para splash screen
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seletor = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        telaPrincipal_textField_mostraDiretorio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        telaPrincipal_textField_endereco = new javax.swing.JTextField();
        telaPrincipal_textField_bairro = new javax.swing.JTextField();
        telaPrincipal_textField_cep = new javax.swing.JTextField();
        telaPrincipal_button_alterar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        telaPrincipal_jLabel_destino = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        barraMenu = new javax.swing.JMenu();
        selecionarArquivo = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();

        seletor.setFileFilter(new MyCustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Diretório");

        telaPrincipal_textField_mostraDiretorio.setEditable(false);

        jLabel2.setText("Endereço:");

        jLabel3.setText("Bairro:");

        jLabel4.setText("CEP:");

        telaPrincipal_textField_endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telaPrincipal_textField_enderecoKeyTyped(evt);
            }
        });

        telaPrincipal_textField_bairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telaPrincipal_textField_bairroKeyTyped(evt);
            }
        });

        telaPrincipal_textField_cep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telaPrincipal_textField_cepKeyTyped(evt);
            }
        });

        telaPrincipal_button_alterar.setText("Alterar");
        telaPrincipal_button_alterar.setEnabled(false);
        telaPrincipal_button_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaPrincipal_button_alterarActionPerformed(evt);
            }
        });

        jLabel5.setText("Destino:");

        telaPrincipal_jLabel_destino.setText(" ");

        barraMenu.setText("Arquivos");

        selecionarArquivo.setText("Importar");
        selecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarArquivoActionPerformed(evt);
            }
        });
        barraMenu.add(selecionarArquivo);

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        barraMenu.add(sair);

        jMenuBar1.add(barraMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telaPrincipal_textField_cep, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(telaPrincipal_textField_bairro)
                            .addComponent(telaPrincipal_textField_mostraDiretorio)
                            .addComponent(telaPrincipal_textField_endereco)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(telaPrincipal_button_alterar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(telaPrincipal_jLabel_destino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(telaPrincipal_textField_mostraDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(telaPrincipal_textField_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(telaPrincipal_textField_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telaPrincipal_textField_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telaPrincipal_jLabel_destino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(telaPrincipal_button_alterar)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarArquivoActionPerformed
        int returnVal = seletor.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = seletor.getSelectedFile();
            telaPrincipal_textField_mostraDiretorio.setText(file.getAbsolutePath());
            System.out.println(file.getAbsolutePath());
        } else {
            System.out.println("File access cancelled by user.");
        }
        if(telaPrincipal_textField_mostraDiretorio.getText().isEmpty()){
            telaPrincipal_button_alterar.setEnabled(false);
        }else {
            telaPrincipal_button_alterar.setEnabled(true);
        }
    }//GEN-LAST:event_selecionarArquivoActionPerformed
    
    private void telaPrincipal_button_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaPrincipal_button_alterarActionPerformed
        String endereco = telaPrincipal_textField_endereco.getText();
        String bairro = telaPrincipal_textField_bairro.getText();
        String cep = telaPrincipal_textField_cep.getText();
        String finalString = endereco + bairro + cep;
        String arquivoOrigem = telaPrincipal_textField_mostraDiretorio.getText();
        String arquivoDestino = arquivoOrigem.replace(".txt", "_ALT.txt");

        System.out.println(finalString);
        System.out.println(arquivoDestino);
        System.out.println(endereco.length());
        System.out.println(bairro.length());
        System.out.println(cep.length());

        int tamanhoEndereco = 60 - endereco.length();
        int tamanhoBairro = 30 - bairro.length();
        int tamanhoCep = 53 - cep.length();
        for (int i = 0; i < tamanhoEndereco; i++) {
            endereco += " ";
        }
        for (int i = 0; i < tamanhoBairro; i++) {
            bairro += " ";
        }
        for (int i = 0; i < tamanhoCep; i++) {
            cep += " ";
        }
        finalString = endereco +  bairro +  cep;
        System.out.println(finalString);
        try {
            List linhas = FileUtil.obterRegistros(arquivoOrigem);
            List linhasNovoArquivo = new LinkedList<String>();

            Iterator linhasIterator = linhas.iterator();

            while (linhasIterator.hasNext()) {
                String linha = (String) linhasIterator.next();
                String campo0 = FileUtil.obterCampoPorPosicao(linha, 1, 7);
                String campo1 = FileUtil.obterCampoPorPosicao(linha, 7, 7);
                String campo2 = FileUtil.obterCampoPorPosicao(linha, 8, 90);
                String campo3 = FileUtil.obterCampoPorPosicao(linha, 93, 93);
                String campo4 = FileUtil.obterCampoPorPosicao(linha, 97, 150);
                if (campo1.endsWith("6")) {
                    linhasNovoArquivo.add(campo0 + finalString);
                    
                } else if (campo1.endsWith("2")) {
                    campo0 = qwerty.FileUtil.obterCampoPorPosicao(linha, 1, 6);
                    linhasNovoArquivo.add(campo0 + campo1 + campo2 + "00" + campo3 + "293" + campo4);
                } else {
                    linhasNovoArquivo.add(linha);
                }
            }
            FileUtil.escreverArquivo(arquivoDestino, linhasNovoArquivo);

        } catch (IOException e) {
            // TODO Auto-generated catch block
            System.err.println("Erro ao obter diretório.");
            e.printStackTrace();
            
        }
        telaPrincipal_jLabel_destino.setText(arquivoDestino);
        telaPrincipal_jLabel_destino.setForeground(Color.blue);

        
    }//GEN-LAST:event_telaPrincipal_button_alterarActionPerformed

    private void telaPrincipal_textField_enderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telaPrincipal_textField_enderecoKeyTyped
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JTextField campo = (JTextField) evt.getSource();
                int posicaoCursor = campo.getCaretPosition();
                campo.setText(campo.getText().toUpperCase());
                if (posicaoCursor != campo.getCaretPosition()) {
                    campo.setCaretPosition(posicaoCursor);
                }
            }
        });
        if (telaPrincipal_textField_endereco.getText().length() > 49) { //limita para o máximo de 50 caracteres
            evt.consume();
        }
        if (evt.getKeyChar() == '!' || evt.getKeyChar() == '@' || evt.getKeyChar() == '#' || evt.getKeyChar() == '#' || evt.getKeyChar() == '$' || evt.getKeyChar() == '%' || evt.getKeyChar() == '¨' || evt.getKeyChar() == '&' || evt.getKeyChar() == '*' || evt.getKeyChar() == ')' || evt.getKeyChar() == '(' || evt.getKeyChar() == '-' || evt.getKeyChar() == '_' || evt.getKeyChar() == '+' || evt.getKeyChar() == '=' || evt.getKeyChar() == '´' || evt.getKeyChar() == '`' || evt.getKeyChar() == '{' || evt.getKeyChar() == 'ª' || evt.getKeyChar() == '[' || evt.getKeyChar() == '^' || evt.getKeyChar() == '~' || evt.getKeyChar() == '}' || evt.getKeyChar() == ']' || evt.getKeyChar() == 'º' || evt.getKeyChar() == '<' || evt.getKeyChar() == ',' || evt.getKeyChar() == '>' || evt.getKeyChar() == '.' || evt.getKeyChar() == ':' || evt.getKeyChar() == ';' || evt.getKeyChar() == '?' || evt.getKeyChar() == '/' || evt.getKeyChar() == '°' || evt.getKeyChar() == '¹' || evt.getKeyChar() == '²' || evt.getKeyChar() == '³' || evt.getKeyChar() == '£' || evt.getKeyChar() == '¢' || evt.getKeyChar() == '¬' || evt.getKeyChar() == '§' || evt.getKeyChar() == 'ª') {
            evt.consume();
        }
    }//GEN-LAST:event_telaPrincipal_textField_enderecoKeyTyped

    private void telaPrincipal_textField_bairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telaPrincipal_textField_bairroKeyTyped
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JTextField campo = (JTextField) evt.getSource();
                int posicaoCursor = campo.getCaretPosition();
                campo.setText(campo.getText().toUpperCase());
                if (posicaoCursor != campo.getCaretPosition()) {
                    campo.setCaretPosition(posicaoCursor);
                }
            }
        });
        if (telaPrincipal_textField_bairro.getText().length() > 39) {// limite de caracteres
            evt.consume();
        }
        if (evt.getKeyChar() == '!' || evt.getKeyChar() == '@' || evt.getKeyChar() == '#' || evt.getKeyChar() == '#' || evt.getKeyChar() == '$' || evt.getKeyChar() == '%' || evt.getKeyChar() == '¨' || evt.getKeyChar() == '&' || evt.getKeyChar() == '*' || evt.getKeyChar() == ')' || evt.getKeyChar() == '(' || evt.getKeyChar() == '-' || evt.getKeyChar() == '_' || evt.getKeyChar() == '+' || evt.getKeyChar() == '=' || evt.getKeyChar() == '´' || evt.getKeyChar() == '`' || evt.getKeyChar() == '{' || evt.getKeyChar() == 'ª' || evt.getKeyChar() == '[' || evt.getKeyChar() == '^' || evt.getKeyChar() == '~' || evt.getKeyChar() == '}' || evt.getKeyChar() == ']' || evt.getKeyChar() == 'º' || evt.getKeyChar() == '<' || evt.getKeyChar() == ',' || evt.getKeyChar() == '>' || evt.getKeyChar() == '.' || evt.getKeyChar() == ':' || evt.getKeyChar() == ';' || evt.getKeyChar() == '?' || evt.getKeyChar() == '/' || evt.getKeyChar() == '°' || evt.getKeyChar() == '¹' || evt.getKeyChar() == '²' || evt.getKeyChar() == '³' || evt.getKeyChar() == '£' || evt.getKeyChar() == '¢' || evt.getKeyChar() == '¬' || evt.getKeyChar() == '§' || evt.getKeyChar() == 'ª') {
            evt.consume();
        }
    }//GEN-LAST:event_telaPrincipal_textField_bairroKeyTyped

    private void telaPrincipal_textField_cepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telaPrincipal_textField_cepKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) { //Verifica se o digito é um numero
            evt.consume();
        }
        if (telaPrincipal_textField_cep.getText().length() > 7) { //verifica o tamanho do texto no textField
            evt.consume();
        }
    }//GEN-LAST:event_telaPrincipal_textField_cepKeyTyped

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new TelaPrincipal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu barraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem selecionarArquivo;
    private javax.swing.JFileChooser seletor;
    private javax.swing.JButton telaPrincipal_button_alterar;
    private javax.swing.JLabel telaPrincipal_jLabel_destino;
    private javax.swing.JTextField telaPrincipal_textField_bairro;
    private javax.swing.JTextField telaPrincipal_textField_cep;
    private javax.swing.JTextField telaPrincipal_textField_endereco;
    private javax.swing.JTextField telaPrincipal_textField_mostraDiretorio;
    // End of variables declaration//GEN-END:variables
}